- name: make crm configuration
  template:
    src=PG-REX9.6_pm_crmgen_env.crm.j2
    dest=/root/PG-REX9.6_pm_crmgen_env.crm
  when: inventory_hostname == ansible_play_hosts[0]

- name: pm_logconv configuration
  template:
    src=pm_logconv.conf.j2
    dest=/etc/pm_logconv.conf
  notify: restart pm_logconv
