- hosts: localhost
  connection: local
  become: false
  gather_facts: no

  tasks:
    - name: make sure the minor revision of PostgreSQL
      set_fact:
        pg_rev: '11.4-1PGDG'
      when: pg_rev is not defined
      tags: postgresql

    - name: Download PostgreSQL 11 packages
      get_url:
        url="https://yum.postgresql.org/11/redhat/rhel-7-x86_64/{{ item }}"
        dest=./roles/pgrex-install/files/
        timeout=60
      with_items:
        - postgresql11-libs-{{ pg_rev }}.rhel7.x86_64.rpm
        - postgresql11-{{ pg_rev }}.rhel7.x86_64.rpm
        - postgresql11-server-{{ pg_rev }}.rhel7.x86_64.rpm
        - postgresql11-docs-{{ pg_rev }}.rhel7.x86_64.rpm
        - postgresql11-contrib-{{ pg_rev }}.rhel7.x86_64.rpm
      tags: postgresql

    # NOTE:
    #   Make sure to change the revision id of OSDN below and
    #   the package version in roles/pgrex-install/tasks/pgrex-optools.yml
    #   accordingly when you update this playbook.
    #   only changing pgrex_package here is NOT sufficient!
    - name: make sure the minor revision of PG-REX tools
      set_fact:
        pgrex_package: 'pg-rex11-1.1-2'
      tags: pg-rex

    - name: Download pg-rex11 optools
      get_url:
        url="https://osdn.net/frs/redir.php?m=iij&f=%2Fpg-rex%2F{{item.rev}}%2F{{item.package}}"
        dest=./roles/pgrex-install/files/
        timeout=20
      with_items:
        - { rev: 71260, package: "{{ pgrex_package }}.tar.gz" }
      tags: pg-rex

    - name: Extract pg-rex11 packages
      shell: |
        cd ./roles/pgrex-install/files/
        tar xfvz {{ pgrex_package }}.tar.gz
        mv {{ pgrex_package }}/*.rpm .
        rm -rf {{ pgrex_package }}/
      tags: pg-rex, extract
