- hosts: localhost
  connection: local
  become: false
  gather_facts: no

  tasks:
    - name: make sure the package revision of PostgreSQL
      set_fact:
        pg_rev: '17.7-1PGDG.rhel9'
      when: pg_rev is not defined
      tags: postgresql
    - name: make sure pg_rev format is valid
      fail:
        msg: |
          'pg_rev' format must look like '17.7-1PGDG.rhel9'
          Hint - the format has been changed so that it must contains rhel revision
      when: '"rhel" not in pg_rev'
      tags: postgresql
    - name: extract major version number of PostgreSQL
      set_fact:
        pg_major: "{{ pg_rev | regex_replace('^(\\d*)\\..*', '\\1') }}"
      tags: postgresql
    - name: make sure the target distribution major version
      set_fact:
        rhel_major: "{{ pg_rev | regex_replace('.*\\.rhel(\\d)', '\\1') }}"
      tags: postgresql

    - name: Download PostgreSQL {{ pg_rev }} packages
      get_url:
        url="https://yum.postgresql.org/{{ pg_major }}/redhat/rhel-{{ rhel_major }}-x86_64/{{ item }}"
        dest=./roles/pgrex-install/files/
        timeout=60
      with_items:
        - postgresql{{ pg_major }}-libs-{{ pg_rev }}.x86_64.rpm
        - postgresql{{ pg_major }}-{{ pg_rev }}.x86_64.rpm
        - postgresql{{ pg_major }}-server-{{ pg_rev }}.x86_64.rpm
        - postgresql{{ pg_major }}-docs-{{ pg_rev }}.x86_64.rpm
        - postgresql{{ pg_major }}-contrib-{{ pg_rev }}.x86_64.rpm
      tags: postgresql

    # NOTE:
    #   Make sure to change the package version in
    #     roles/pgrex-install/tasks/pgrex-optools.yml
    #   accordingly when you change the PG_REX version
    #   only changing PG_REX variable here is NOT sufficient!
    - name: specify the release package of the PG-REX tools
      set_fact:
        #PG_REX: { tag: "PG-REX_15_4", package: "pg-rex15-4.0-1.tar.gz" }
        #PG_REX: { tag: "PG-REX_15_5", package: "pg-rex15-5.0-1.tar.gz" }
        #PG_REX: { tag: "PG-REX_16_5", package: "pg-rex16-5.0-1-tar.gz" }
        PG_REX: { tag: "PG-REX_17_1", package: "pg-rex17-1.0-1.tar.gz" }
      tags: pg-rex, extract

    - name: Download the pg-rex all in one package
      get_url:
        url="https://github.com/ossc-db/PG-REX-tools/releases/download/{{ PG_REX.tag }}/{{ PG_REX.package }}"
        dest=./roles/pgrex-install/files/
      tags: pg-rex

    - name: Extract pg-rex packages
      shell: |
        cd ./roles/pgrex-install/files/
        tar xfvz {{ PG_REX.package }} --transform='s,.*/,,' \*.rpm
      tags: pg-rex, extract
