- hosts: localhost
  connection: local
  become: false
  gather_facts: no

  tasks:
    - name: Download PostgreSQL 11 packages
      get_url:
        url="https://yum.postgresql.org/11/redhat/rhel-7-x86_64/{{ item }}"
        dest=./roles/pgrex-install/files/
        timeout=60
      with_items:
        - postgresql11-libs-11.1-1PGDG.rhel7.x86_64.rpm
        - postgresql11-11.1-1PGDG.rhel7.x86_64.rpm
        - postgresql11-server-11.1-1PGDG.rhel7.x86_64.rpm
        - postgresql11-contrib-11.1-1PGDG.rhel7.x86_64.rpm
        - postgresql11-docs-11.1-1PGDG.rhel7.x86_64.rpm
      tags: postgresql

    - name: Download pg-rex10 optools
      get_url:
        url="https://osdn.net/frs/redir.php?m=iij&f=%2Fpg-rex%2F{{item.rev}}%2F{{item.package}}"
        dest=./roles/pgrex-install/files/
        timeout=20
      with_items:
        - { rev: 70626, package: pg-rex11-1.0.0-1.tar.gz }
      tags: pg-rex

    - name: Extract pg-rex11 packages
      shell: |
        cd ./roles/pgrex-install/files/
        tar xfvz pg-rex11-1.0.0-1.tar.gz
        mv pg-rex11-1.0.0-1/*.rpm .
        rm -rf pg-rex11-1.0.0-1/
      tags: pg-rex, extract
