- hosts: localhost
  connection: local
  become: false
  gather_facts: no
  vars_files:
    - vars/pgrex-version.yml

  tasks:
    - name: make sure the minor revision of PostgreSQL
      set_fact:
        pg_rev: "{{ pg_rev | default(pg_rev_default) }}"
      tags: always
    - name: extract major version number of PostgreSQL
      set_fact:
        pg_major: "{{ pg_rev | regex_replace('^(\\d*)\\..*', '\\1') }}"
      tags: postgresql
    - name: make sure the target distribution major version
      set_fact:
        rhel_major: "{{ pg_rev | regex_replace('.*\\.rhel(\\d)', '\\1') }}"
      tags: postgresql

    - name: Download PostgreSQL {{ pg_rev }} packages
      get_url:
        url="https://yum.postgresql.org/{{ pg_major }}/redhat/rhel-{{ rhel_major }}-x86_64/{{ item }}"
        dest=./roles/pgrex-install/files/
        timeout=60
      with_items:
        - postgresql{{ pg_major }}-libs-{{ pg_rev }}.x86_64.rpm
        - postgresql{{ pg_major }}-{{ pg_rev }}.x86_64.rpm
        - postgresql{{ pg_major }}-server-{{ pg_rev }}.x86_64.rpm
        - postgresql{{ pg_major }}-docs-{{ pg_rev }}.x86_64.rpm
        - postgresql{{ pg_major }}-contrib-{{ pg_rev }}.x86_64.rpm
      tags: postgresql

    - name: Download the pg-rex all in one package
      get_url:
        url="https://github.com/ossc-db/PG-REX-tools/releases/download/{{ PG_REX.tag }}/{{ PG_REX.package }}"
        dest=./roles/pgrex-install/files/
      when: PG_REX.package is defined
      tags: pg-rex

    - name: Extract pg-rex packages
      shell: |
        cd ./roles/pgrex-install/files/
        tar xfvz {{ PG_REX.package }} --transform='s,.*/,,' \*.rpm
      when: PG_REX.package is defined
      tags: pg-rex, extract

    - name: Download the pg-rex RPMs indivisually when all in one package is not available
      get_url:
        url="https://github.com/ossc-db/PG-REX-tools/releases/download/{{ PG_REX.tag }}/{{ item }}"
        dest=./roles/pgrex-install/files/
      with_items: "{{ PG_REX.rpms }}"
      when: PG_REX.package is not defined
      tags: pg-rex
